# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: mushroom_monitor
    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      run: echo "${{ secrets.CR_PAT }}" | docker login -u ${{ secrets.CR_USER }} --password-stdin


    - name: Build docker container
      run: |
        docker build -t ${{ secrets.CR_USER }}/mushroom_monitor:latest . -f ./build/Dockerfile
        docker push ${{ secrets.CR_USER }}/mushroom_monitor:latestu

    - name: Replace docker compose placeholders
      env: 
        PASSWORD: ${{ secrets.PASSWORD }}
        USER: ${{ secrets.USER }}
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
      run: |
        sed -i 's/<PASSWORD>/'$PASSWORD'/g' ${{ github.workspace }}/build/compose.yaml
        sed -i 's/<USER>/'$USER'/g' ${{ github.workspace }}/build/compose.yaml
        sed -i 's/<HOST>/'$HOST'/g' ${{ github.workspace }}/build/compose.yaml
        sed -i 's/<PORT>/'$PORT'/g' ${{ github.workspace }}/build/compose.yaml

    - name: Run docker compose
      run: |
       docker compose -f ./build/compose.yaml up -d 
